name: remindcall
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  flutter_background_service: any
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  audioplayers: ^6.6.0
  flutter_tts: ^4.2.5
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.4
  wakelock_plus: ^1.2.8
  google_generative_ai: ^0.4.0
  speech_to_text: ^7.3.0
  permission_handler: ^11.3.0
  firebase_core: ^2.24.0
  firebase_auth: ^4.15.0
  cloud_firestore: ^4.15.0
  firebase_messaging: ^14.7.0
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/ringtone.mp3
    - assets/icon.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
