// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRNbBYbVJtcSuJlJwRo4sXpxrR6-gTWRk',
    appId: '1:38453214981:web:f5c32dd5d51bbb8288016c',
    messagingSenderId: '38453214981',
    projectId: 'callminder-d8372',
    authDomain: 'callminder-d8372.firebaseapp.com',
    storageBucket: 'callminder-d8372.firebasestorage.app',
    measurementId: 'G-JXZ6B9T74H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXL_tZa217xCYKi17im3d1MxQsOUVgSQI',
    appId: '1:38453214981:android:ae0d3aabc4b4541788016c',
    messagingSenderId: '38453214981',
    projectId: 'callminder-d8372',
    storageBucket: 'callminder-d8372.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWaX-Mj82rLEu9q7gogFXCi9DwaYo9YPU',
    appId: '1:38453214981:ios:45a100bf904a7bbb88016c',
    messagingSenderId: '38453214981',
    projectId: 'callminder-d8372',
    storageBucket: 'callminder-d8372.firebasestorage.app',
    androidClientId: '38453214981-vf6tg435urnlufc5fhu648dgocrpftl2.apps.googleusercontent.com',
    iosClientId: '38453214981-v2us409v5sg7uofuo2c9ghv9o7v78cgn.apps.googleusercontent.com',
    iosBundleId: 'com.example.remindcall',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWaX-Mj82rLEu9q7gogFXCi9DwaYo9YPU',
    appId: '1:38453214981:ios:45a100bf904a7bbb88016c',
    messagingSenderId: '38453214981',
    projectId: 'callminder-d8372',
    storageBucket: 'callminder-d8372.firebasestorage.app',
    androidClientId: '38453214981-vf6tg435urnlufc5fhu648dgocrpftl2.apps.googleusercontent.com',
    iosClientId: '38453214981-v2us409v5sg7uofuo2c9ghv9o7v78cgn.apps.googleusercontent.com',
    iosBundleId: 'com.example.remindcall',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRNbBYbVJtcSuJlJwRo4sXpxrR6-gTWRk',
    appId: '1:38453214981:web:abbf33754d5c242f88016c',
    messagingSenderId: '38453214981',
    projectId: 'callminder-d8372',
    authDomain: 'callminder-d8372.firebaseapp.com',
    storageBucket: 'callminder-d8372.firebasestorage.app',
    measurementId: 'G-G4C7YJ8PE9',
  );

}